### ISSUE TITLE
Error after upload

### ISSUE THREAD

**Issue by cyberwombat** [jkettmann/relay-authentication#1]
After creating a new post as publisher the list of post yields this error:

```
[Error] Warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props 
[Error] TypeError: null is not an object (evaluating 'props.viewer.post.title')
```

**Comment by jkettmann** [comment]
Thanks for your interest. I can reproduce the issue. I'll probably have a look at it tomorrow.

**Comment by jkettmann** [comment]
Please check again. I realized that my error message was a bit different and the error occurred on the posts detail page.

**Comment by cyberwombat** [comment]
The second error is gone and that was the showstopper. It now works though I still get the first warning. For example right after login (on that note I have to press twice on the login button for it to work - safari latest)

**Comment by jkettmann** [comment]
Great. That first warning is react related. I will have to clean up the project anyway at some point. Some things are still quite dirty. For now I just don't have the time
