### ISSUE TITLE
Arrow function should not return assignment  no-return-assign

### ISSUE THREAD

**Issue by davidhibbard1** [jkettmann/relay-authentication#11]
<div ref={ref => (this.container = ref)} style={styles.root}>
relay-authentication/client/components/post/PostList.js
  54:17  error  Arrow function should not return assignment  no-return-assign

I used this fix
      <div ref={(arg) => { this.container = arg }} style={styles.root}>

**Comment by jkettmann** [comment]
@davidhibbard1 Your fix was correct, but I rather used a class method. Makes it a bit cleaner I think
