### ISSUE TITLE
Out date dependency

### ISSUE THREAD

**Issue by katopz** [jkettmann/relay-authentication#7]
I think many off them is out date already especially `webpack`. Can you update it to present version?

**Comment by jkettmann** [comment]
Thanks for your feedback. I unfortunately couldn't find any time to update the project the last months. I'll try to find some time the next days, but I'll be on a longer vacation in a few days, so don't expect too much ;-)

**Comment by nithincscubet** [comment]
Below dependencies also should be updated
material-ui@0.16.3
react-tap-event-plugin@2.0.0

**Comment by jkettmann** [comment]
I'll try to release a whole new version soon.

**Comment by jkettmann** [comment]
Just to keep you informed ;-): I uploaded a new version using Relay Modern. I also did a lot of clean up and simplifications.
